---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: crif-shop-test-scc-storeuser
  labels:
    backstage.io/kubernetes-id: crif-shop-test
    app.kubernetes.io/name: crif-shop-test
    rht-gitops.com/janus-argocd: crif-shop-test
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:crif-shop-test:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: crif-shop-test-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: crif-shop-test
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:crif-shop-test:storeuseradmin-sa
